public class GcdOfStrings {
    public static void main(String[] args) {
        System.out.println(
                gcdOfStrings("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"));
        System.out.println(
                gcdOfStrings("ABABABAB",
                        "ABAB"));
        System.out.println(
                gcdOfStrings(
                        "VAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIG",
                        "VAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGVVAWRHBJIAYJFQECBVIGV"));
    }

    public static String gcdOfStrings(String str1, String str2) {
        String flag = "";
        int length = str1.length() >= str2.length() ? str1.length() : str2.length();

        if (str1.equals(str2))
            return str1;

        if (str1.split(str2).length == 0)
            return str2;

        if (str2.split(str1).length == 0)
            return str1;

        for (int i = 1; i < length; i++) {
            if (str1.length() == i)
                break;
            String tempFlag = str1.substring(0, i);

            String[] x = str2.split(tempFlag);
            String[] y = str1.split(tempFlag);

            if (x.length == 0 && y.length == 0)
                flag = tempFlag;
        }
        return flag;
    }
}
